### ISSUE TITLE
example demo

### ISSUE THREAD

**Issue by Thanmai-C** [rollymaduk/react-native-collapsible-tab-header#2]
Hi,
can you please share or update the read me with gif of the example.

**Comment by rollymaduk** [comment]
Hi @Thanmai-C , I have had a bit of challenge getting my emulator to work on my machine, and I have not found the time to fix that, but you can run the examples in the [examples folder](https://github.com/rollymaduk/react-native-collapsible-tab-header/tree/master/examples) to get an idea of how it works. I plan to refactor the code base and get gifs working once I can find the time. PR's are welcome

**Comment by Thanmai-C** [comment]
Ok sure, thank u

**Comment by ansal-exp** [comment]
Okay. I know this is closed. Anyway I have just implemented the library example in snack. I hope it will be helpfull for someone. https://snack.expo.io/rkDy2zYYM :-)

**Comment by rollymaduk** [comment]
hey @ansal-exp this is great! well done and thanks. Although when I tried to run the snack, it times out. perhaps the data loading is taking too long, I don't know but do you care to trouble shoot and fix?

**Comment by Thanmai-C** [comment]
I get an error saying"Failed to install 'react-native-collapsible-tab-header':Attempted to import missing module '@expo/vector-icons/Zocial' imported from components/index.js"

**Comment by ansal-exp** [comment]
@Thanmai-C It seems like a snack issue, as it was cleared when I just edited and reloaded the app.No need to re-open this issue. you can close it now.
@rollymaduk It also seems like a snack issue. I got it once but it disappeared when I reloaded the app.

If you still can't access/getting errors from the snack link, Please see this video using the below link. In the video it behaves a bit different than the expected scroll functionality.

https://drive.google.com/file/d/17JJTpJ6ZmMSdwXQahiNci-kMH0JtbaGp/view?usp=sharing

edit: 
The  Snack and the video is displaying RTL functionality too. Hence, @rollymaduk can happily announce that this Library supports RTL.
